name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=test_secret_key" >> .env
          echo "JWT_SECRET_KEY=test_jwt_secret_key" >> .env
          echo "SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@localhost:5432/test_db" >> .env

      # Run database migrations
      - name: Run migrations
        run: |
          source venv/bin/activate
          flask db upgrade

      # Run tests
      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest --maxfail=5 --disable-warnings
