name: CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      - name: Configure Environment Variables
        run: |
         
          echo "SECRET_KEY=mysecret" >> backend/.env
          echo "JWT_SECRET_KEY=myjwtsecret" >> backend/.env
          echo "SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@localhost:5432/test_db" >> backend/.env

   
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=backend" >> $GITHUB_ENV
        
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest 

